---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-critical-500
value: 500000
globalDefault: false
description: "This priority class is for critical priority workloads."

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-high-400
value: 400000
globalDefault: false
description: "This priority class is for high priority workloads."

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-medium-300
value: 300000
globalDefault: false
description: "This priority class is for medium priority workloads."

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-normal-200
value: 200000
globalDefault: true
description: "This priority class is for normal priority workloads."

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: priority-low-100
value: 100000
globalDefault: false
description: "This priority class is for low priority workloads."
